import { FormEvent, useState } from "react";
import { useNavigate } from "@tanstack/react-router";
import { Loader2 } from "lucide-react";
import { supabase } from "../lib/supabase";

export function CustomerAuth() {
  const navigate = useNavigate(); const [signup,setSignup]=useState(false); const [email,setEmail]=useState(""); const [name,setName]=useState(""); const [password,setPassword]=useState(""); const [confirm,setConfirm]=useState(""); const [error,setError]=useState(""); const [message,setMessage]=useState(""); const [loading,setLoading]=useState(false);
  async function submit(e:FormEvent){e.preventDefault();setError("");setMessage("");if(!supabase){setError("Autenticação indisponível.");return}if(signup&&(!name.trim()||password.length<6||password!==confirm)){setError(!name.trim()?"Informe seu nome completo.":password.length<6?"A senha deve ter pelo menos 6 caracteres.":"As senhas não coincidem.");return}setLoading(true);try{const result=signup?await supabase.auth.signUp({email:email.trim(),password,options:{data:{full_name:name.trim()}}}):await supabase.auth.signInWithPassword({email:email.trim(),password});if(result.error)throw result.error;if(signup&&!result.data.session)setMessage("Confira seu e-mail para confirmar a conta.");else await navigate({to:"/conta"});}catch(err){setError(err instanceof Error?err.message:"Não foi possível concluir.")}finally{setLoading(false)}}
  async function reset(){if(!supabase||!email.includes("@")){setError("Informe seu e-mail.");return}setLoading(true);const {error:e}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:`${window.location.origin}/conta`});setLoading(false);e?setError(e.message):setMessage("Enviamos as instruções para seu e-mail.")}
  return <main className="min-h-screen bg-background px-5 py-24 text-foreground"><section className="mx-auto max-w-md rounded-3xl border border-border bg-card p-6 sm:p-10"><p className="text-center text-xs uppercase tracking-[.3em] text-primary">LEH_CLOSETT GLOW</p><h1 className="mt-5 text-center text-4xl font-semibold">{signup?"Crie sua conta.":"Bem-vinda de volta."}</h1><p className="mt-3 text-center text-sm text-muted-foreground">{signup?"Faça parte da experiência Glow.":"Entre para acessar sua conta."}</p><form onSubmit={submit} className="mt-8 space-y-4">{signup&&<label className="block text-sm">Nome completo<input required value={name} onChange={e=>setName(e.target.value)} className="mt-2 h-12 w-full rounded-xl border border-input bg-background px-4"/></label>}<label className="block text-sm">E-mail<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} className="mt-2 h-12 w-full rounded-xl border border-input bg-background px-4"/></label><label className="block text-sm">Senha<input required type="password" value={password} onChange={e=>setPassword(e.target.value)} className="mt-2 h-12 w-full rounded-xl border border-input bg-background px-4"/></label>{signup&&<label className="block text-sm">Confirmar senha<input required type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} className="mt-2 h-12 w-full rounded-xl border border-input bg-background px-4"/></label>}{error&&<p role="alert" className="rounded-xl border border-destructive/40 p-3 text-sm text-destructive">{error}</p>}{message&&<p role="status" className="rounded-xl border border-primary/30 p-3 text-sm text-primary">{message}</p>}<button disabled={loading} className="flex h-12 w-full items-center justify-center gap-2 rounded-full bg-primary text-sm font-bold uppercase text-primary-foreground disabled:opacity-60">{loading&&<Loader2 className="animate-spin" size={16}/>} {signup?"Criar conta":"Entrar"}</button></form>{!signup&&<button onClick={reset} className="mt-5 w-full text-sm text-muted-foreground hover:text-primary">Esqueci minha senha</button>}<p className="mt-6 text-center text-sm text-muted-foreground">{signup?"Já tem uma conta?":"Ainda não tem uma conta?"} <button onClick={()=>setSignup(!signup)} className="font-semibold text-primary">{signup?"Entrar":"Criar minha conta"}</button></p></section></main>;
}
