/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PedidoConfirmadoRouteImport } from './routes/pedido-confirmado'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as CatalogoIndexRouteImport } from './routes/catalogo/index'
import { Route as CatalogoIdRouteImport } from './routes/catalogo/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoConfirmadoRoute = PedidoConfirmadoRouteImport.update({
  id: '/pedido-confirmado',
  path: '/pedido-confirmado',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const CatalogoIndexRoute = CatalogoIndexRouteImport.update({
  id: '/catalogo/',
  path: '/catalogo/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoIdRoute = CatalogoIdRouteImport.update({
  id: '/catalogo/$id',
  path: '/catalogo/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/conta': typeof ContaRoute
  '/favoritos': typeof FavoritosRoute
  '/login': typeof LoginRoute
  '/pedido-confirmado': typeof PedidoConfirmadoRoute
  '/admin/login': typeof AdminLoginRoute
  '/catalogo/$id': typeof CatalogoIdRoute
  '/catalogo/': typeof CatalogoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/conta': typeof ContaRoute
  '/favoritos': typeof FavoritosRoute
  '/login': typeof LoginRoute
  '/pedido-confirmado': typeof PedidoConfirmadoRoute
  '/admin/login': typeof AdminLoginRoute
  '/catalogo/$id': typeof CatalogoIdRoute
  '/catalogo': typeof CatalogoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/conta': typeof ContaRoute
  '/favoritos': typeof FavoritosRoute
  '/login': typeof LoginRoute
  '/pedido-confirmado': typeof PedidoConfirmadoRoute
  '/admin/login': typeof AdminLoginRoute
  '/catalogo/$id': typeof CatalogoIdRoute
  '/catalogo/': typeof CatalogoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/carrinho'
    | '/checkout'
    | '/conta'
    | '/favoritos'
    | '/login'
    | '/pedido-confirmado'
    | '/admin/login'
    | '/catalogo/$id'
    | '/catalogo/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/carrinho'
    | '/checkout'
    | '/conta'
    | '/favoritos'
    | '/login'
    | '/pedido-confirmado'
    | '/admin/login'
    | '/catalogo/$id'
    | '/catalogo'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/carrinho'
    | '/checkout'
    | '/conta'
    | '/favoritos'
    | '/login'
    | '/pedido-confirmado'
    | '/admin/login'
    | '/catalogo/$id'
    | '/catalogo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CarrinhoRoute: typeof CarrinhoRoute
  CheckoutRoute: typeof CheckoutRoute
  ContaRoute: typeof ContaRoute
  FavoritosRoute: typeof FavoritosRoute
  LoginRoute: typeof LoginRoute
  PedidoConfirmadoRoute: typeof PedidoConfirmadoRoute
  CatalogoIdRoute: typeof CatalogoIdRoute
  CatalogoIndexRoute: typeof CatalogoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido-confirmado': {
      id: '/pedido-confirmado'
      path: '/pedido-confirmado'
      fullPath: '/pedido-confirmado'
      preLoaderRoute: typeof PedidoConfirmadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/catalogo/': {
      id: '/catalogo/'
      path: '/catalogo'
      fullPath: '/catalogo/'
      preLoaderRoute: typeof CatalogoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo/$id': {
      id: '/catalogo/$id'
      path: '/catalogo/$id'
      fullPath: '/catalogo/$id'
      preLoaderRoute: typeof CatalogoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CarrinhoRoute: CarrinhoRoute,
  CheckoutRoute: CheckoutRoute,
  ContaRoute: ContaRoute,
  FavoritosRoute: FavoritosRoute,
  LoginRoute: LoginRoute,
  PedidoConfirmadoRoute: PedidoConfirmadoRoute,
  CatalogoIdRoute: CatalogoIdRoute,
  CatalogoIndexRoute: CatalogoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
